name: "test-action"
on: [issues,pull_request]

jobs:
  test:
    name: setup environment
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    # (optional) set the node version if you do not want to use the one specified in Github environment
    # see Software installed on GitHub-hosted runners
    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '12.x'
    - run: npm install
    - uses: ./
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}