name: mast joke mara
on:
  pull_request:
  issues:
  types: [opened]

jobs:
  comment:
    if: github.event_name=='pull_request' || github.event_name=='issues'
    runs-on: ubuntu-latest
    steps:
      - name: mast joke mara
        uses: deep5050/MastJokeMara@main
        id: MastJokeMara
        with:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}